# Generated by Django 3.0.7 on 2020-06-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('num_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('logged_in', models.BooleanField()),
            ],
        ),
    ]
