# Generated by Django 3.0.7 on 2020-07-01 20:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='sign_in_time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 1, 20, 23, 57, 661096, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
