# Generated by Django 3.0.7 on 2020-07-01 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200701_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='sign_in_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
