# Generated by Django 3.0.7 on 2020-07-02 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200701_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='sign_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
