# Generated by Django 3.1.1 on 2020-10-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_appearance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='team_role',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
