# Generated by Django 3.0.7 on 2020-10-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20201001_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='num_hours_in_person',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='member',
            name='num_hours_virtual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
