# Generated by Django 3.0.7 on 2020-10-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20201002_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='activity',
            field=models.CharField(default='', max_length=50),
        ),
    ]
