# Generated by Django 3.0.7 on 2020-10-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_appearance_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='location',
            field=models.CharField(default='virtual', max_length=10),
        ),
    ]
